var newDate= new Date();
//newDate.setDate(30);
var toDayDate=newDate.getDate();	
var toDay=newDate.getDay();
let thisWeek=["monday","tuesday","wednesday","thursday","friday","saturday","sunday"];
let thisMonth=["jan","feb","mar","apr","may","jun","jly","aug","sep","oct","nov","dec"];
//newDate.setMonth(3);
var month=newDate.getMonth();
//newDate.setFullYear(2000);
var year=newDate.getFullYear();
//newDate.setHours(03);
var hrs=newDate.getHours();
//newDate.setMinutes(30);
var min=newDate.getMinutes();
//newDate.setSeconds(40);
var sec=newDate.getSeconds();
//newDate.setMilliseconds(750);
var milliSec=newDate.getMilliseconds();
console.log("date",toDayDate,"day",thisWeek[toDay],"month",thisMonth[month],"year",year);
console.log("hrs",hrs,"min",min,"sec",sec,"millisec",milliSec);
